services:
  - type: web
    name: skillaura-backend
    env: python
    rootDir: skillaura_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 # or whichever version is suitable
