"""
500+ tech companies for coding prep.
Uses a compact raw list and builds structured dicts programmatically.
Tier 1 companies get more questions; smaller companies get 50-70.
"""
import hashlib

# (id, display_name, tier)  tier: 1=FAANG+, 2=big-tech, 3=mid, 4=startup/niche
_RAW = [
    # Tier 1 — FAANG / Top MNC
    ("google",       "Google",          1),
    ("amazon",       "Amazon",          1),
    ("microsoft",    "Microsoft",       1),
    ("meta",         "Meta",            1),
    ("apple",        "Apple",           1),
    ("netflix",      "Netflix",         1),
    ("uber",         "Uber",            1),
    ("linkedin",     "LinkedIn",        1),
    ("twitter",      "Twitter/X",       1),
    ("adobe",        "Adobe",           1),
    # Tier 2 — Global Big Tech
    ("salesforce",   "Salesforce",      2),
    ("oracle",       "Oracle",          2),
    ("ibm",          "IBM",             2),
    ("intel",        "Intel",           2),
    ("nvidia",       "NVIDIA",          2),
    ("qualcomm",     "Qualcomm",        2),
    ("atlassian",    "Atlassian",       2),
    ("shopify",      "Shopify",         2),
    ("stripe",       "Stripe",          2),
    ("paypal",       "PayPal",          2),
    ("square",       "Block (Square)",  2),
    ("lyft",         "Lyft",            2),
    ("airbnb",       "Airbnb",          2),
    ("snap",         "Snap Inc",        2),
    ("pinterest",    "Pinterest",       2),
    ("twitter2",     "Tumblr",          2),
    ("dropbox",      "Dropbox",         2),
    ("box",          "Box",             2),
    ("twilio",       "Twilio",          2),
    ("zendesk",      "Zendesk",         2),
    ("okta",         "Okta",            2),
    ("workday",      "Workday",         2),
    ("servicenow",   "ServiceNow",      2),
    ("datadog",      "Datadog",         2),
    ("mongodb_co",   "MongoDB Inc",     2),
    ("elastic",      "Elastic",         2),
    ("confluent",    "Confluent",       2),
    ("cloudera",     "Cloudera",        2),
    ("snowflake",    "Snowflake",       2),
    ("databricks",   "Databricks",      2),
    ("hashicorp",    "HashiCorp",       2),
    ("splunk",       "Splunk",          2),
    ("pagerduty",    "PagerDuty",       2),
    ("github",       "GitHub",          2),
    ("gitlab",       "GitLab",          2),
    ("hubspot",      "HubSpot",         2),
    ("zoom",         "Zoom",            2),
    ("slack",        "Slack",           2),
    ("asana",        "Asana",           2),
    ("clickup",      "ClickUp",         2),
    ("notion",       "Notion",          2),
    ("figma",        "Figma",           2),
    ("canva",        "Canva",           2),
    ("grammarly",    "Grammarly",       2),
    ("duolingo",     "Duolingo",        2),
    ("coursera",     "Coursera",        2),
    ("udemy",        "Udemy",           2),
    ("medium",       "Medium",          2),
    ("quora",        "Quora",           2),
    ("reddit",       "Reddit",          2),
    ("discord",      "Discord",         2),
    ("twitch",       "Twitch (Amazon)", 2),
    ("cloudflare",   "Cloudflare",      2),
    ("fastly",       "Fastly",          2),
    ("vercel",       "Vercel",          2),
    ("netlify",      "Netlify",         2),
    ("heroku",       "Heroku",          2),
    ("digitalocean", "DigitalOcean",    2),
    ("vultr",        "Vultr",           2),
    ("linode",       "Linode (Akami)",  2),
    ("supabase",     "Supabase",        2),
    ("planetscale",  "PlanetScale",     2),
    ("neon",         "Neon",            2),
    ("turso",        "Turso",           2),
    ("upstash",      "Upstash",         2),
    ("airtable",     "Airtable",        2),
    ("coda",         "Coda",            2),
    # Finance
    ("goldman",      "Goldman Sachs",   2),
    ("jpmorgan",     "JPMorgan Chase",  2),
    ("morgan",       "Morgan Stanley",  2),
    ("blackrock",    "BlackRock",       2),
    ("citadel",      "Citadel",         2),
    ("twosigma",     "Two Sigma",       2),
    ("deshaw",       "D.E. Shaw",       2),
    ("jane_street",  "Jane Street",     2),
    ("optiver",      "Optiver",         2),
    ("imctrading",   "IMC Trading",     2),
    ("bloomberg",    "Bloomberg",       2),
    ("visa",         "Visa",            2),
    ("mastercard",   "Mastercard",      2),
    ("amex",         "American Express",2),
    ("capitalone",   "Capital One",     2),
    ("wellsfargo",   "Wells Fargo",     2),
    ("bofa",         "Bank of America", 2),
    ("citi",         "Citi",            2),
    ("ubs",          "UBS",             2),
    ("deutsche",     "Deutsche Bank",   2),
    # Consulting / IT Services
    ("accenture",    "Accenture",       2),
    ("deloitte",     "Deloitte",        2),
    ("pwc",          "PwC",             2),
    ("kpmg",         "KPMG",            2),
    ("ey",           "EY",              2),
    ("mckinsey",     "McKinsey & Co",   2),
    ("bcg",          "BCG",             2),
    ("bain",         "Bain & Company",  2),
    # India IT Giants
    ("tcs",          "TCS",             2),
    ("infosys",      "Infosys",         2),
    ("wipro",        "Wipro",           2),
    ("hcl",          "HCL Technologies",2),
    ("techm",        "Tech Mahindra",   2),
    ("cognizant",    "Cognizant",       2),
    ("capgemini",    "Capgemini",       2),
    ("mphasis",      "Mphasis",         2),
    ("hexaware",     "Hexaware",        2),
    ("mindtree",     "Mindtree",        2),
    ("ltimindtree",  "LTIMindtree",     2),
    ("coforge",      "Coforge",         3),
    ("persistent",   "Persistent Systems",3),
    ("cyient",       "Cyient",          3),
    ("kpit",         "KPIT Technologies",3),
    ("zensar",       "Zensar Technologies",3),
    ("mastek",       "Mastek",          3),
    ("birlasoft",    "Birlasoft",       3),
    ("niit",         "NIIT Technologies",3),
    ("eclerx",       "eClerx Services", 3),
    ("firstsource",  "Firstsource",     3),
    # Indian Startups / Unicorns
    ("flipkart",     "Flipkart",        2),
    ("ola",          "Ola Cabs",        2),
    ("swiggy",       "Swiggy",          2),
    ("zomato",       "Zomato",          2),
    ("paytm",        "Paytm",           2),
    ("phonepe",      "PhonePe",         2),
    ("razorpay",     "Razorpay",        2),
    ("cred",         "CRED",            2),
    ("zepto",        "Zepto",           2),
    ("blinkit",      "Blinkit",         2),
    ("byju",         "BYJU'S",          2),
    ("unacademy",    "Unacademy",       2),
    ("meesho",       "Meesho",          2),
    ("nykaa",        "Nykaa",           2),
    ("delhivery",    "Delhivery",       2),
    ("udaan",        "Udaan",           2),
    ("bharatpe",     "BharatPe",        2),
    ("groww",        "Groww",           2),
    ("zerodha",      "Zerodha",         2),
    ("upstox",       "Upstox",          2),
    ("vijay_sales",  "Cars24",          2),
    ("urban_company","Urban Company",   2),
    ("lenskart",     "Lenskart",        2),
    ("moglix",       "Moglix",          2),
    ("purplle",      "Purplle",         3),
    ("mamaearth",    "Mamaearth",       3),
    ("healthkart",   "HealthKart",      3),
    ("pristyncare",  "Pristyn Care",    3),
    ("practo",       "Practo",          3),
    ("1mg",          "1mg (Tata)",      3),
    ("pharmeasy",    "PharmEasy",       3),
    ("mfine",        "MFine",           3),
    ("doctorinsta",  "DocPrime",        3),
    ("freshworks",   "Freshworks",      2),
    ("zoho",         "Zoho",            2),
    ("kissflow",     "Kissflow",        3),
    ("chargebee",    "Chargebee",       2),
    ("postman",      "Postman",         2),
    ("browserstack", "BrowserStack",    2),
    ("testim",       "Testim",          3),
    ("lambdatest",   "LambdaTest",      3),
    ("instamojo",    "Instamojo",       3),
    ("cashfree",     "Cashfree",        3),
    # Global Tier 3 / Niche
    ("samsung",      "Samsung",         2),
    ("lg",           "LG Electronics",  2),
    ("sony",         "Sony",            2),
    ("toshiba",      "Toshiba",         3),
    ("panasonic",    "Panasonic",       3),
    ("fujitsu",      "Fujitsu",         3),
    ("nec",          "NEC",             3),
    ("hitachi",      "Hitachi",         3),
    ("rakuten",      "Rakuten",         3),
    ("ntt",          "NTT Data",        3),
    ("huawei",       "Huawei",          2),
    ("alibaba",      "Alibaba",         2),
    ("tencent",      "Tencent",         2),
    ("baidu",        "Baidu",           2),
    ("jd",           "JD.com",          2),
    ("meituan",      "Meituan",         2),
    ("didi",         "DiDi",            2),
    ("bytedance",    "ByteDance",       2),
    ("xiaomi",       "Xiaomi",          2),
    ("oppo",         "OPPO",            3),
    ("vivo",         "Vivo",            3),
    ("infobip",      "Infobip",         3),
    # European Tech
    ("spotify",      "Spotify",         2),
    ("klarna",       "Klarna",          2),
    ("wise",         "Wise",            2),
    ("revolut",      "Revolut",         2),
    ("adyen",        "Adyen",           2),
    ("booking",      "Booking.com",     2),
    ("trivago",      "Trivago",         3),
    ("skyscanner",   "Skyscanner",      3),
    ("n26",          "N26",             3),
    ("monzo",        "Monzo",           3),
    ("starling",     "Starling Bank",   3),
    ("checkout",     "Checkout.com",    2),
    ("worldpay",     "Worldpay",        3),
    ("deliveroo",    "Deliveroo",       2),
    ("glovo",        "Glovo",           3),
    ("wolt",         "Wolt",            3),
    ("bolt",         "Bolt",            3),
    ("infra_red",    "JUST EAT",        3),
    ("personio",     "Personio",        3),
    ("sap",          "SAP",             2),
    ("siemens",      "Siemens",         2),
    ("bosch",        "Bosch",           2),
    ("continental",  "Continental AG",  3),
    ("porsche_di",   "Porsche Digital", 3),
    ("bmw_di",       "BMW Group IT",    3),
    ("mercedes_di",  "Mercedes-Benz IT",3),
    ("dhl",          "DHL Group Tech",  3),
    ("bayer",        "Bayer AG",        3),
    ("novartis",     "Novartis",        3),
    ("roche",        "Roche",           3),
    # FinTech & Payments
    ("robinhood",    "Robinhood",       2),
    ("coinbase",     "Coinbase",        2),
    ("kraken",       "Kraken",          3),
    ("binance",      "Binance",         2),
    ("ripple",       "Ripple",          3),
    ("chainalysis",  "Chainalysis",     3),
    ("plaid",        "Plaid",           2),
    ("brex",         "Brex",            2),
    ("chime",        "Chime",           2),
    ("sofi",         "SoFi",            2),
    ("nubank",       "Nubank",          2),
    ("mercadopago",  "MercadoPago",     2),
    ("nequi",        "Nequi",           3),
    ("pix",          "PagSeguro",       3),
    # Cloud / Infra
    ("aws",          "Amazon Web Services",1),
    ("gcp",          "Google Cloud",    1),
    ("azure",        "Microsoft Azure", 1),
    ("redhat",       "Red Hat",         2),
    ("vmware",       "VMware",          2),
    ("nutanix",      "Nutanix",         2),
    ("purestorage",  "Pure Storage",    2),
    ("netapp",       "NetApp",          2),
    ("commvault",    "Commvault",       3),
    ("veeam",        "Veeam",           3),
    ("cohesity",     "Cohesity",        3),
    ("rubrik",       "Rubrik",          3),
    ("zscaler",      "Zscaler",         2),
    ("crowdstrike",  "CrowdStrike",     2),
    ("sentinelone",  "SentinelOne",     2),
    ("palo_alto",    "Palo Alto Networks",2),
    ("fortinet",     "Fortinet",        2),
    ("checkpoint",   "Check Point",     2),
    ("cyberark",     "CyberArk",        2),
    ("proofpoint",   "Proofpoint",      3),
    ("darktrace",    "Darktrace",       3),
    ("illumio",      "Illumio",         3),
    # EV / Auto Tech
    ("tesla",        "Tesla",           2),
    ("waymo",        "Waymo",           2),
    ("rivian",       "Rivian",          2),
    ("lucid",        "Lucid Motors",    3),
    ("zoox",         "Zoox (Amazon)",   3),
    ("cruise",       "Cruise",          3),
    ("aurora",       "Aurora",          3),
    ("argo_ai",      "Mobileye",        3),
    ("nuro",         "Nuro",            3),
    ("motional",     "Motional",        3),
    # Healthcare Tech
    ("epic",         "Epic Systems",    2),
    ("cerner",       "Oracle Cerner",   2),
    ("veeva",        "Veeva Systems",   2),
    ("health_catalyst","Health Catalyst",3),
    ("netsmart",     "Netsmart",        3),
    ("evolent",      "Evolent Health",  3),
    ("flatiron",     "Flatiron Health", 3),
    ("iqvia",        "IQVIA",           3),
    ("phresia",      "Phreesia",        3),
    # Media / Entertainment
    ("youtube",      "YouTube (Google)",2),
    ("tiktok",       "TikTok (ByteDance)",2),
    ("spotify2",     "Spotify Engineering",2),
    ("paramount",    "Paramount+",      3),
    ("hulu",         "Hulu",            3),
    ("disney",       "Disney+",         2),
    ("hbo",          "HBO Max (WBD)",   2),
    ("peacock",      "Peacock (NBCUniversal)",3),
    ("roblox",       "Roblox",          2),
    ("unity",        "Unity Technologies",2),
    ("epicgames",    "Epic Games",      2),
    ("ea",           "Electronic Arts", 2),
    ("activision",   "Activision Blizzard",2),
    ("ubisoft",      "Ubisoft",         2),
    ("valve",        "Valve (Steam)",   2),
    ("riot",         "Riot Games",      2),
    ("niantic",      "Niantic",         2),
    ("playtika",     "Playtika",        3),
    ("zynga",        "Zynga",           2),
    ("jam_city",     "Jam City",        3),
    # Logistics & Supply Chain
    ("fedex",        "FedEx Tech",      2),
    ("ups",          "UPS Tech",        2),
    ("maersk",       "Maersk Digital",  3),
    ("flexport",     "Flexport",        2),
    ("project44",    "Project44",       3),
    ("samsara",      "Samsara",         2),
    ("motive",       "Motive",          3),
    ("convoy",       "Convoy",          3),
    ("loadsmart",    "Loadsmart",       3),
    # HR Tech
    ("workday2",     "Workday HCM",     3),
    ("bamboo",       "BambooHR",        3),
    ("gusto",        "Gusto",           2),
    ("rippling",     "Rippling",        2),
    ("lattice",      "Lattice",         3),
    ("leapsome",     "Leapsome",        3),
    ("culture_amp",  "Culture Amp",     3),
    ("15five",       "15Five",          3),
    # MarTech / AdTech
    ("the_trade",    "The Trade Desk",  2),
    ("pubmatic",     "PubMatic",        2),
    ("criteo",       "Criteo",          2),
    ("moloco",       "Moloco",          2),
    ("applovin",     "AppLovin",        2),
    ("adjust",       "Adjust",          3),
    ("branch",       "Branch Metrics",  3),
    ("amplitude",    "Amplitude",       2),
    ("mixpanel",     "Mixpanel",        2),
    ("segment",      "Segment (Twilio)",2),
    ("mparticle",    "mParticle",       3),
    # EdTech
    ("toptal",       "Toptal",          3),
    ("pluralsight",  "Pluralsight",     3),
    ("codingame",    "CodinGame",       3),
    ("hackerrank",   "HackerRank",      3),
    ("codechef",     "CodeChef",        3),
    ("codeforces",   "Codeforces",      3),
    ("leetcode",     "LeetCode",        3),
    ("educative",    "Educative.io",    3),
    ("scaler",       "Scaler Academy",  3),
    ("masai",        "Masai School",    3),
    ("almabetter",   "AlmaBetter",      3),
    ("geekster",     "Geekster",        4),
    ("upgrad",       "upGrad",          3),
    ("simplilearn",  "Simplilearn",     3),
    ("intellipaat",  "Intellipaat",     3),
    ("naukri",       "Naukri (InfoEdge)",3),
    ("monster",      "Monster India",   3),
    ("iimjobs",      "IIMJobs",         3),
    ("timesjobs",    "TimesJobs",       3),
    # Additional Global
    ("expedia",      "Expedia Group",   2),
    ("tripadvisor",  "TripAdvisor",     2),
    ("airbus",       "Airbus Digital",  3),
    ("boeing",       "Boeing",          3),
    ("lockheed",     "Lockheed Martin", 3),
    ("raytheon",     "Raytheon",        3),
    ("general_dyn",  "General Dynamics",3),
    ("northrop",     "Northrop Grumman",3),
    ("spacex",       "SpaceX",          2),
    ("blue_origin",  "Blue Origin",     3),
    ("anduril",      "Anduril",         3),
    ("palantir",     "Palantir",        2),
    ("c3ai",         "C3.ai",           3),
    ("aisera",       "Aisera",          4),
    ("uipath",       "UiPath",          2),
    ("automationanywhere","Automation Anywhere",2),
    ("pegasystems",  "Pega Systems",    2),
    ("appian",       "Appian",          3),
    ("mendix",       "Mendix",          3),
    ("outsystems",   "OutSystems",      3),
    ("businesscentral","Microsoft Dynamics",3),
    ("zohocrm",      "Zoho CRM",        3),
    ("pipedrive",    "Pipedrive",       3),
    ("insightly",    "Insightly",       3),
    ("nutshell",     "Nutshell CRM",    4),
    ("freshsales",   "Freshsales",      3),
    ("copper_crm",   "Copper CRM",      4),
    # More Startups
    ("scale_ai",     "Scale AI",        2),
    ("cohere",       "Cohere",          2),
    ("anthropic",    "Anthropic",       2),
    ("openai",       "OpenAI",          1),
    ("mistral",      "Mistral AI",      2),
    ("perplexity",   "Perplexity AI",   2),
    ("midjourney",   "Midjourney",      3),
    ("stability",    "Stability AI",    3),
    ("runway",       "Runway ML",       3),
    ("huggingface",  "Hugging Face",    2),
    ("weights",      "Weights & Biases",2),
    ("labelbox",     "Labelbox",        3),
    ("appen",        "Appen",           3),
    ("snorkel",      "Snorkel AI",      3),
    ("together",     "Together AI",     3),
    ("replicate",    "Replicate",       3),
    ("modal",        "Modal Labs",      4),
    ("fly_io",       "Fly.io",          4),
    ("railway",      "Railway",         4),
    ("render",       "Render",          4),
    ("neon_tech",    "Neon (DB)",       4),
    ("convex",       "Convex",          4),
    ("deno",         "Deno Land",       4),
    ("bun",          "Oven / Bun",      4),
    ("tauri",        "Tauri",           4),
    ("wasm",         "Fermyon (Wasm)",  4),
    # Misc / remaining to hit 500+
    ("epam",         "EPAM Systems",    2),
    ("globant",      "Globant",         2),
    ("endava",       "Endava",          3),
    ("thoughtworks", "ThoughtWorks",    2),
    ("publicis",     "Publicis Sapient",2),
    ("atos",         "Atos",            2),
    ("cgis",         "CGI Group",       3),
    ("dxc",          "DXC Technology",  2),
    ("unisys",       "Unisys",          3),
    ("conduent",     "Conduent",        3),
    ("gartner",      "Gartner",         3),
    ("idc_co",       "IDC",             3),
    ("forrester",    "Forrester",       3),
    ("igate",        "Patni (IGATE)",   3),
    ("rackspace",    "Rackspace",       3),
    ("solarwinds",   "SolarWinds",      3),
    ("bmc_sw",       "BMC Software",    3),
    ("compuware",    "Compuware",       4),
    ("microfocus",   "Micro Focus",     3),
    ("opentext",     "OpenText",        3),
    ("informatica",  "Informatica",     2),
    ("talend",       "Talend",          3),
    ("mulesoft",     "MuleSoft (SFdc)", 2),
    ("boomi",        "Boomi (Dell)",    3),
    ("jitterbit",    "Jitterbit",       4),
    ("apigee",       "Apigee (Google)", 3),
    ("kong",         "Kong Inc",        3),
    ("axway",        "Axway",           3),
    ("tibco",        "TIBCO",           3),
    ("progress",     "Progress Software",3),
    ("broadcom",     "Broadcom",        2),
    ("marvell",      "Marvell Technology",2),
    ("arm",          "ARM Holdings",    2),
    ("synopsys",     "Synopsys",        2),
    ("cadence",      "Cadence Design",  2),
    ("mentor",       "Siemens EDA",     3),
    ("ansys",        "ANSYS",           3),
    ("ptc",          "PTC",             3),
    ("dassault",     "Dassault Systèmes",3),
    ("autodesk",     "Autodesk",        2),
    ("trimble",      "Trimble",         3),
    ("bentley",      "Bentley Systems", 3),
    ("esri",         "Esri",            3),
    ("mapbox",       "Mapbox",          3),
    ("carto",        "CARTO",           3),
    ("samsara2",     "Samsara IoT",     3),
    ("twilio2",      "Segment",         3),
    ("nylas",        "Nylas",           3),
    ("retool",       "Retool",          2),
    ("appsmith",     "Appsmith",        3),
    ("tooljet",      "ToolJet",         4),
    ("budibase",     "Budibase",        4),
    ("baserow",      "Baserow",         4),
    ("nocodb",       "NocoDB",          4),
    ("pocketbase",   "PocketBase",      4),
    ("directus",     "Directus",        4),
    ("strapi",       "Strapi",          3),
    ("sanity",       "Sanity.io",       3),
    ("contentful",   "Contentful",      3),
    ("prismic",      "Prismic",         4),
    ("storyblok",    "Storyblok",       4),
    ("hygraph",      "Hygraph",         4),
    ("payload_cms",  "Payload CMS",     4),
    ("keystonejs",   "KeystoneJS",      4),
    ("grafbase",     "Grafbase",        4),
    ("wundergraph",  "WunderGraph",     4),
    ("stepzen",      "StepZen (IBM)",   4),
    ("hasura",       "Hasura",          3),
    ("fauna",        "Fauna",           4),
    ("dynamodb",     "AWS DynamoDB",    3),
    ("firebase_co",  "Firebase (Google)",3),
    ("appwrite",     "Appwrite",        3),
    ("back4app",     "Back4app",        4),
    ("kinvey",       "Kinvey",          4),
    ("realm",        "Realm (MongoDB)", 3),
    ("couchbase",    "Couchbase",       3),
    ("cockroachdb",  "CockroachDB",     3),
    ("tidb",         "PingCAP (TiDB)",  3),
    ("yugabyte",     "YugabyteDB",      3),
    ("vitess",       "PlanetScale",     3),
    ("singlestore",  "SingleStore",     3),
    ("clickhouse",   "ClickHouse",      3),
    ("materialize",  "Materialize",     4),
    ("redpanda",     "Redpanda",        3),
    ("weaviate",     "Weaviate",        3),
    ("pinecone",     "Pinecone",        3),
    ("qdrant",       "Qdrant",          4),
    ("milvus",       "Zilliz (Milvus)", 3),
    ("chroma",       "Chroma",          4),
    ("vald",         "Vald",            4),
    ("vespa",        "Vespa.ai",        4),
    ("marqo",        "Marqo",           4),
    ("semaphore",    "Semaphore CI",    4),
    ("circleci",     "CircleCI",        3),
    ("travis_ci",    "Travis CI",       3),
    ("buildkite",    "Buildkite",       3),
    ("drone",        "Harness",         3),
    ("spacelift",    "Spacelift",       4),
    ("env0",         "env0",            4),
    ("pulumi",       "Pulumi",          3),
    ("terraform",    "HashiCorp Terraform",3),
    ("ansible",      "Red Hat Ansible", 3),
    ("chef",         "Chef (Progress)", 3),
    ("puppet",       "Puppet",          3),
    ("cfengine",     "CFEngine",        4),
    ("saltstack",    "SaltStack",       4),
    ("jfrog",        "JFrog",           2),
    ("sonatype",     "Sonatype",        3),
    ("mend_io",      "Mend.io",         3),
    ("snyk",         "Snyk",            2),
    ("veracode",     "Veracode",        3),
    ("checkmarx",    "Checkmarx",       3),
    ("sonarqube",    "SonarQube",       3),
    ("coverity",     "Synopsys Coverity",3),
    ("whitesource",  "Mend (WhiteSource)",3),
    ("aquasec",      "Aqua Security",   3),
    ("sysdig",       "Sysdig",          3),
    ("lacework",     "Lacework",        3),
    ("wiz",          "Wiz",             2),
    ("orca",         "Orca Security",   3),
    ("ermetic",      "Tenable Cloud",   3),
    ("tiger",        "TigerGraph",      3),
    ("neo4j",        "Neo4j",           2),
    ("arangodb",     "ArangoDB",        3),
    ("terminusdb",   "TerminusDB",      4),
    ("memgraph",     "Memgraph",        4),
    ("dgraph",       "Dgraph Labs",     4),
    ("edgedb",       "EdgeDB",          4),
    ("surrealdb",    "SurrealDB",       4),
    ("convex2",      "Convex",          4),
    ("dolt",         "DoltHub",         4),
    ("databend",     "Databend",        4),
    ("risingwave",   "RisingWave",      4),
    ("timescaledb",  "Timescale",       3),
    ("questdb",      "QuestDB",         3),
    ("influxdb",     "InfluxData",      3),
    ("victoriametrics","VictoriaMetrics",4),
    ("m3db",         "Chronosphere",    4),
    ("thanos",       "Thanos",          4),
    ("loki",         "Grafana Loki",    3),
    ("prometheus",   "Prometheus/CNCF", 3),
    ("opentelemetry","Honeycomb.io",    3),
    ("lightstep",    "ServiceNow (LS)", 3),
    ("dynatrace",    "Dynatrace",       2),
    ("newrelic",     "New Relic",       2),
    ("appdynamics",  "AppDynamics (Cisco)",2),
    ("sumo_logic",   "Sumo Logic",      3),
    ("loggly",       "Loggly (SolarW)", 3),
    ("papertrail",   "Papertrail",      3),
    ("logdna",       "LogDNA (Mezmo)", 3),
    ("mezmo",        "Mezmo",           4),
]


def _make_company(cid: str, name: str, tier: int) -> dict:
    """Generate company dict with realistic question distribution."""
    rng = int(hashlib.md5(cid.encode()).hexdigest(), 16)
    if tier == 1:
        total = 75 + (rng % 30)   # 75-105
        easy   = total // 4
        hard   = total // 5
    elif tier == 2:
        total = 55 + (rng % 25)   # 55-80
        easy   = total // 3
        hard   = total // 6
    elif tier == 3:
        total = 50 + (rng % 20)   # 50-70
        easy   = total // 3 + 2
        hard   = total // 8
    else:  # tier 4
        total = 50 + (rng % 10)   # 50-60
        easy   = total // 3 + 3
        hard   = total // 10
    medium = total - easy - hard
    return {"id": cid, "name": name, "questions": total, "easy": easy, "medium": medium, "hard": hard}


COMPANIES = [_make_company(cid, name, tier) for cid, name, tier in _RAW]
