"""
Extra coding questions generated from a compact list.
Merged into CODING_QUESTIONS in interview_data.py.
Each entry: (id, title, difficulty, topic, frequency, acceptance)
"""

_Q = [
    ("q011","Contains Duplicate","Easy","Array",88,61),
    ("q012","Best Time to Buy and Sell Stock","Easy","Array",92,54),
    ("q013","Product of Array Except Self","Medium","Array",85,65),
    ("q014","Maximum Product Subarray","Medium","Dynamic Programming",80,34),
    ("q015","Find Minimum in Rotated Sorted Array","Medium","Binary Search",76,49),
    ("q016","Search in Rotated Sorted Array","Medium","Binary Search",83,39),
    ("q017","3Sum","Medium","Two Pointers",90,34),
    ("q018","Container With Most Water","Medium","Two Pointers",86,54),
    ("q019","Sum of Two Integers","Medium","Bit Manipulation",72,51),
    ("q020","Number of 1 Bits","Easy","Bit Manipulation",70,72),
    ("q021","Counting Bits","Easy","Bit Manipulation",75,74),
    ("q022","Missing Number","Easy","Bit Manipulation",80,64),
    ("q023","Reverse Bits","Easy","Bit Manipulation",68,57),
    ("q024","Climbing Stairs II","Easy","Dynamic Programming",60,52),
    ("q025","Coin Change","Medium","Dynamic Programming",88,42),
    ("q026","Longest Increasing Subsequence","Medium","Dynamic Programming",84,52),
    ("q027","Longest Common Subsequence","Medium","Dynamic Programming",78,57),
    ("q028","Word Break","Medium","Dynamic Programming",82,45),
    ("q029","Combination Sum","Medium","Backtracking",80,69),
    ("q030","House Robber","Medium","Dynamic Programming",85,49),
    ("q031","House Robber II","Medium","Dynamic Programming",76,40),
    ("q032","Decode Ways","Medium","Dynamic Programming",77,33),
    ("q033","Unique Paths","Medium","Dynamic Programming",78,63),
    ("q034","Jump Game","Medium","Greedy",84,38),
    ("q035","Palindromic Substrings","Medium","Dynamic Programming",78,68),
    ("q036","Longest Palindromic Substring","Medium","Dynamic Programming",87,33),
    ("q037","Group Anagrams","Medium","Hash Map",88,67),
    ("q038","Top K Frequent Elements","Medium","Heap",86,63),
    ("q039","Find Median from Data Stream","Hard","Heap",78,52),
    ("q040","Merge K Sorted Lists","Hard","Heap",82,53),
    ("q041","Word Search","Medium","Backtracking",82,40),
    ("q042","Word Search II","Hard","Backtracking",72,38),
    ("q043","Palindrome Partitioning","Medium","Backtracking",76,65),
    ("q044","Subsets","Medium","Backtracking",82,75),
    ("q045","Permutations","Medium","Backtracking",84,76),
    ("q046","Letter Combinations of a Phone Number","Medium","Backtracking",82,57),
    ("q047","Generate Parentheses","Medium","Backtracking",86,74),
    ("q048","N-Queens","Hard","Backtracking",70,67),
    ("q049","Serialize and Deserialize Binary Tree","Hard","Tree",76,56),
    ("q050","Binary Tree Maximum Path Sum","Hard","Tree",78,39),
    ("q051","Diameter of Binary Tree","Easy","Tree",82,57),
    ("q052","Balanced Binary Tree","Easy","Tree",78,47),
    ("q053","Same Tree","Easy","Tree",80,58),
    ("q054","Subtree of Another Tree","Easy","Tree",76,46),
    ("q055","Lowest Common Ancestor of a BST","Medium","Tree",82,61),
    ("q056","Convert Sorted Array to BST","Easy","Tree",74,72),
    ("q057","Validate Binary Search Tree","Medium","Tree",83,32),
    ("q058","Kth Smallest Element in a BST","Medium","Tree",80,71),
    ("q059","Construct Binary Tree from Preorder and Inorder","Medium","Tree",76,61),
    ("q060","Binary Tree Level Order Traversal","Medium","BFS",86,65),
    ("q061","Binary Tree Right Side View","Medium","BFS",82,64),
    ("q062","Course Schedule","Medium","Graph",84,49),
    ("q063","Course Schedule II","Medium","Graph",78,48),
    ("q064","Number of Connected Components","Medium","Graph",76,64),
    ("q065","Graph Valid Tree","Medium","Graph",74,45),
    ("q066","Alien Dictionary","Hard","Graph",72,35),
    ("q067","Pacific Atlantic Water Flow","Medium","Graph",74,52),
    ("q068","Clone Graph","Medium","Graph",78,54),
    ("q069","Rotting Oranges","Medium","BFS",80,53),
    ("q070","Word Ladder","Hard","BFS",78,37),
    ("q071","Minimum Height Trees","Medium","Graph",72,38),
    ("q072","Longest Consecutive Sequence","Medium","Hash Map",85,47),
    ("q073","Encode and Decode Strings","Medium","String",74,39),
    ("q074","Minimum Window Substring","Hard","Sliding Window",82,42),
    ("q075","Sliding Window Maximum","Hard","Sliding Window",76,47),
    ("q076","Permutation in String","Medium","Sliding Window",80,44),
    ("q077","Longest Substring with At Most K Distinct","Medium","Sliding Window",74,46),
    ("q078","Reverse String","Easy","String",72,77),
    ("q079","Reverse Words in a String","Medium","String",76,32),
    ("q080","Valid Anagram","Easy","String",82,63),
    ("q081","Valid Palindrome","Easy","String",82,44),
    ("q082","Longest Common Prefix","Easy","String",80,42),
    ("q083","Roman to Integer","Easy","String",82,60),
    ("q084","Integer to Roman","Medium","String",72,65),
    ("q085","Spiral Matrix","Medium","Array",80,47),
    ("q086","Rotate Image","Medium","Array",82,73),
    ("q087","Set Matrix Zeroes","Medium","Array",78,53),
    ("q088","Sort Colors","Medium","Two Pointers",82,65),
    ("q089","4Sum","Medium","Two Pointers",72,37),
    ("q090","Remove Duplicates from Sorted Array","Easy","Array",78,54),
    ("q091","Move Zeroes","Easy","Array",82,61),
    ("q092","Find the Duplicate Number","Medium","Array",80,59),
    ("q093","First Missing Positive","Hard","Array",76,38),
    ("q094","Trapping Rain Water","Hard","Stack",82,60),
    ("q095","Daily Temperatures","Medium","Stack",80,66),
    ("q096","Car Fleet","Medium","Stack",72,50),
    ("q097","Evaluate Reverse Polish Notation","Medium","Stack",78,47),
    ("q098","Min Stack","Medium","Stack",82,52),
    ("q099","Next Greater Element","Easy","Stack",74,72),
    ("q100","Largest Rectangle in Histogram","Hard","Stack",76,44),
    ("q101","Design Add and Search Words","Medium","Trie",72,43),
    ("q102","Implement Trie","Medium","Trie",78,65),
    ("q103","Word Search II (Trie)","Hard","Trie",70,38),
    ("q104","Kth Largest Element in Array","Medium","Heap",84,66),
    ("q105","Task Scheduler","Medium","Heap",76,57),
    ("q106","Reorganize String","Medium","Heap",74,55),
    ("q107","Find K Closest Elements","Medium","Binary Search",72,48),
    ("q108","Search a 2D Matrix","Medium","Binary Search",82,47),
    ("q109","Time Based Key-Value Store","Medium","Binary Search",74,53),
    ("q110","Median of Two Sorted Arrays","Hard","Binary Search",84,37),
]


def _make_q(qid, title, diff, topic, freq, acc):
    slug = title.lower().replace(" ", "_").replace("-", "_")
    desc = f"Solve the classic '{title}' problem. Apply {topic} techniques to find an optimal solution."
    py_code = f"class Solution:\n    def solve(self):\n        # Implement {title}\n        pass"
    js_code = f"// Implement {title}\nfunction solve() {{\n    // Your solution here\n}}"
    java_code = f"class Solution {{\n    public void solve() {{\n        // Implement {title}\n    }}\n}}"
    cpp_code = f"class Solution {{\npublic:\n    void solve() {{\n        // Implement {title}\n    }}\n}};"
    return {
        "id": qid, "title": title, "difficulty": diff, "topic": topic,
        "companies": [], "frequency": freq, "acceptance": acc,
        "description": desc,
        "examples": [{"input": "See problem description", "output": "Expected output", "explanation": ""}],
        "constraints": ["See full problem on LeetCode"],
        "starter_code": {"python": py_code, "javascript": js_code, "java": java_code, "cpp": cpp_code},
        "test_cases": [],
    }


EXTRA_QUESTIONS = [_make_q(*row) for row in _Q]
