// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaBZnHC5fgqAnKxbzVBW_DDb9kB9097RM',
    appId: '1:994830157258:web:a7d0b6dd916b2d0cf53b33',
    messagingSenderId: '994830157258',
    projectId: 'skilloura',
    authDomain: 'skilloura.firebaseapp.com',
    storageBucket: 'skilloura.firebasestorage.app',
    measurementId: 'G-9YJGNECSWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXQohNovoP8NNVr04EZNM2bOYKIyQWl0',
    appId: '1:994830157258:android:dac6a623f62cce52f53b33',
    messagingSenderId: '994830157258',
    projectId: 'skilloura',
    storageBucket: 'skilloura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkgpCi3QwMo8RMXJ3-vF6AT6Ba5I_SlRU',
    appId: '1:994830157258:ios:3b12a7a3f026b35af53b33',
    messagingSenderId: '994830157258',
    projectId: 'skilloura',
    storageBucket: 'skilloura.firebasestorage.app',
    iosBundleId: 'com.example.skillaura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkgpCi3QwMo8RMXJ3-vF6AT6Ba5I_SlRU',
    appId: '1:994830157258:ios:3b12a7a3f026b35af53b33',
    messagingSenderId: '994830157258',
    projectId: 'skilloura',
    storageBucket: 'skilloura.firebasestorage.app',
    iosBundleId: 'com.example.skillaura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaBZnHC5fgqAnKxbzVBW_DDb9kB9097RM',
    appId: '1:994830157258:web:ed8539a8ce268193f53b33',
    messagingSenderId: '994830157258',
    projectId: 'skilloura',
    authDomain: 'skilloura.firebaseapp.com',
    storageBucket: 'skilloura.firebasestorage.app',
    measurementId: 'G-T2C5E844CF',
  );
}
